#!/bin/bash

#SBATCH -J longranger
#SBATCH -o ../stdout/longranger.%j.out
#SBATCH -e ../stderr/longranger.%j.err
##SBATCH -D 

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --time=48:00:00

export PATH=../Software/longranger-2.2.2/:$PATH

## Only change this: #######################################################
FQ_DIR="../Elephant_project/TSW/genomic_data/10x"
NAME="TSW_3884"
OUT_DIR="../Elephant_project/TSW/intermediates/Longranger"
############################################################################

DEINTERLEAVE="../Software/deinterleave_fastq.sh"

mkdir -p $OUT_DIR
cd $OUT_DIR
longranger basic --id=$NAME --fastqs=$FQ_DIR --localcores 16

cd $NAME/outs
$DEINTERLEAVE < <(zcat barcoded.fastq.gz) debarcoded.1.fastq.gz debarcoded.2.fastq.gz compress
