#!/bin/bash

## Full installation ######################################################
##conda create -n PURGEDUPS_env
##conda activate PURGEDUPS_env
##conda install -c bioconda purge_dups bwa samtools
##conda install -c conda-forge matplotlib
###########################################################################

#SBATCH -J purge_dups
#SBATCH -o ../stdout/purge_dups.%j.out
#SBATCH -e ../stderr/purge_dups.%j.err
##SBATCH -D 

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=24
#SBATCH --mem=48G
#SBATCH --time=72:00:00

export PATH=../Software/anaconda3/bin:$PATH
source activate PURGEDUPS_env


## Only change this: ############################################
OUT_DIR="../Elephant_project/TSW/intermediates/purge_dups"
NAME="3884_pri"
PRI_ASM="../Elephant_project/TSW/intermediates/Supernova/pseudohap2/3884.1.fasta"
ASM_NAME=$(basename $PRI_ASM .fasta)
#ALT_ASM=""
FQ_1="../Elephant_project/TSW/intermediates/trimmed/barcoded.1_val_1.fq.gz"
FQ_2="../Elephant_project/TSW/intermediates/trimmed/barcoded.2_val_2.fq.gz"
FQ_NAME=$(basename $FQ_2 .2_val_2.fq.gz)
#################################################################


mkdir -p $OUT_DIR/$NAME/idx


#A: align Illumina PE (or 10x DEbarcoded) reads and generate BAM files, then calculate read depth histogram and base-level read depth
# Indexing the reference (This should be done one time)
cd $OUT_DIR/$NAME/idx
bwa index -p $ASM_NAME -a bwtsw $PRI_ASM
cd $OUT_DIR/$NAME
bwa mem -t 18 $OUT_DIR/$NAME/idx/$ASM_NAME $FQ_1 $FQ_2 | samtools view -@ 6 -b -o - > $FQ_NAME\.bam
ngscstat $FQ_NAME\.bam
calcuts TX.stat > cutoffs 2>calcults.log
HIST_PLOT="../Software/purge_dups/scripts/hist_plot.py"
python3 $HIST_PLOT -c cutoffs TX.stat TX.png

# to manually change cutoff
LOW=5
MID=22
UP=87
CUTOFFS=$LOW\_$MID\_$UP
#calcuts -l$LOW -m$MID -u$UP TX.stat > cutoffs_$CUTOFFS


#B: Split an assembly and do a self-self alignment
cd $OUT_DIR/$NAME
split_fa $PRI_ASM > $ASM_NAME\.split
minimap2 -t 18 -xasm5 -DP $ASM_NAME\.split $ASM_NAME\.split | pigz -p 6 -c - > $ASM_NAME\.split.self.paf.gz


#C: Purge haplotigs and overlaps
cd $OUT_DIR/$NAME
purge_dups -2 -T cutoffs_$CUTOFFS -c TX.base.cov $ASM_NAME\.split.self.paf.gz > dups_$CUTOFFS\.bed 2> purge_dups_$CUTOFFS\.log


#D: Get purged primary and haplotig sequences from draft assembly
cd $OUT_DIR/$NAME
get_seqs -e dups_$CUTOFFS\.bed $PRI_ASM 
mv purged.fa purged_$CUTOFFS\.fa
mv hap.fa hap_$CUTOFFS\.fa


#E: Merge hap_$CUTOFFS\.fa and $ALT_ASM and redo the above steps !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


















