#!/bin/bash

## Full installation ######################################################
##conda create -n MERQURY_env -c conda-forge -c bioconda merqury openjdk=11
###########################################################################

#SBATCH -J meryl
#SBATCH -o ../stdout/meryl.%j.out
#SBATCH -e ../stderr/meryl.%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
##SBATCH -w b004
#SBATCH --qos=standard
#SBATCH --cpus-per-task=32
#SBATCH --mem=32G
#SBATCH --time=24:00:00

export PATH=../Software/anaconda3/bin:$PATH
source activate MERQURY_env

GENOMESCOPE2="../Software/genomescope2.0/genomescope.R"




# for paired reads (if 10x, shoud be already barcode-trimmed)

## Only change this: ###############################################
FQ_DIR="../Elephant_project/TSW/intermediates/trimming"
OUT_DIR="../Elephant_project/TSW/evaluation/meryl"
GENOMESCOPE_OUT_DIR="../Elephant_project/TSW/evaluation/genomescope"
####################################################################


# build meryl database for each file
mkdir -p $OUT_DIR

for i in $(ls $FQ_DIR/*.fq.gz)
do
        NAME=$(basename $i .fq.gz)
        meryl k=21 memory=32 threads=32 count $i output $OUT_DIR/$NAME\.meryl
done

# merge all databases
meryl k=21 memory=32 threads=32 union-sum output $OUT_DIR/3884.meryl $OUT_DIR/*.meryl

# get histogram for genomescope
meryl histogram $OUT_DIR/3884.meryl | sed 's/\t/ /g' > $OUT_DIR/3884.hist

# run genomescope
mkdir -p $GENOMESCOPE_OUT_DIR
Rscript $GENOMESCOPE2 -i $OUT_DIR/3884.hist -o $GENOMESCOPE_OUT_DIR -k 21 --fitted_hist
