#!/bin/bash

#SBATCH -J meryl
#SBATCH -o ../stdout/meryl.%j.out
#SBATCH -e ../stderr/meryl.%j.err
#SBATCH -D ../Elephant_project/TSW/evaluation/meryl

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=32
#SBATCH --mem=32G
#SBATCH --time=48:00:00

export PATH=../Software/meryl-1.3/bin/:$PATH

meryl count k=21 memory=32 threads=32 ../Elephant_project/TSW/genomic_data/10x/trimmed/_3884/outs/barcoded.fastq.gz output 3884_10x.meryl

meryl threads=1 print ../Elephant_project/TSW/evaluation/meryl/3884_10x.meryl | sed -e 's/\t/ /g' > 3884_10x.histo
